### ISSUE TITLE
Documentation generation for IPMI, OS, SNMP and Stack templates

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/rabe-zabbix#25]
We need a way to generate the documentation for IPMI, OS, SNMP and Stack templates, as we currently do for the App templates.

- [x] IPMI templates (addressed and merged with #29)
- [x] OS templates (addressed and merged with #38)
- [x] SNMP templates (addressed with 8934b4a, 60d7c85 and c8f184f)
- [ ] Stack templates

**Comment by paraenggu** [comment]
@hairmare Any ideas on how we should threat the missing stack templates?

**Comment by hairmare** [comment]
@paraenggu I guess the stack templates need some special consideration since they are rather different from the regular templates. Maybe an xslt just for them makes sense?

**Comment by hairmare** [comment]
closing this because the new ansible stack has stacks as a first class citizen
