### ISSUE TITLE
Wrong trigger name in Template_App_MD-RAID_active

### ISSUE THREAD

**Issue by jan2000** [radiorabe/rabe-zabbix#28]
https://github.com/radiorabe/rabe-zabbix/blob/aa30b5165287763d3d8126f4e5f98f356a80ad39/app/MD-RAID/Template_App_MD-RAID_active.xml#L474

Should be:
```xml
<name>RAID array device MD {#MD_RAID_RAID_DEV_NAME} has {ITEM.VALUE1} degraded device(s) on {HOST.NAME}</name>
```

**Comment by paraenggu** [comment]
Thank you!
