### ISSUE TITLE
Regarding Debian

### ISSUE THREAD

**Issue by Arcticold** [radiorabe/rabe-zabbix#40]
I saw that the package is available for CentOS. Do you think it would work on Debian as well? We could really use that, but our system is on Debian.

**Comment by paraenggu** [comment]
Most of it should work without problems on other Linux distributions. However, there might be some external commands which could be too old on legacy LTS distros.

Just try to follow the manual installation instructions of a given template. Most of the templates which depend on external commands, also contain some basic debug instructions, in case something doesn't work as expected.

Feel free to open up another issue in case you have a problem with a specific template on Debian.
