### ISSUE TITLE
cant import xml file to zabbix server 2.4.2 version

### ISSUE THREAD

**Issue by linooks** [radiorabe/rabe-zabbix#58]
Can you advise please? cant upgrade my existing zabbix server yet.

**Comment by paraenggu** [comment]
Hi @linooks 

please note, that all templates are developed and tested against the current Zabbix LTS version (3.0), therefore your older Zabbix installation might miss some required features. 

Can you please post the affected template name as well as the corresponding error message?

**Comment by linooks** [comment]
Hello @paraenggu , Thank you for the prompt response.

Template is Template_App_LVM_active.xml, I wanted to use it to monitor my kvm server volume group.

Unfortunately the error I only have is "ERROR: Import failed Unknown import version"

**Comment by paraenggu** [comment]
You would have to adapt the XML to match with the [older schema](https://www.zabbix.com/documentation/2.4/manual/xml_export_import). In a first step you would want to change the [`<version>3.0</version>`](https://github.com/radiorabe/rabe-zabbix/blob/03ff13dd37ecf2586daffd661f006ea317a106c9/app/LVM/Template_App_LVM_active.xml#L3). However, this is probably a painful process and I don't know if you will succeed at last.
Is there a specific reason why you can't upgrade to a more recent and supported Zabbix version?

**Comment by linooks** [comment]
I thought so. Ill close this one. Thank you so much, appreciate the response.
