### ISSUE TITLE
template import

### ISSUE THREAD

**Issue by sieku** [radiorabe/rabe-zabbix#59]
Template_App_MD-RAID_active.xml
Cannot read XML: (41) Specification mandate value for attribute data-pjax-transient [Line: 43 | Column: 91].

Zabbix 3.4

**Comment by hairmare** [comment]
Make sure that you download the [raw version](https://raw.githubusercontent.com/radiorabe/rabe-zabbix/master/app/MD-RAID/Template_App_MD-RAID_active.xml), use git clone or, [download a zip](https://github.com/radiorabe/rabe-zabbix/archive/master.zip).
