### ISSUE TITLE
Inbound utilization is very high (> 90 % over 1h) on [...] interface cpu ()

### ISSUE THREAD

**Issue by linuxlurak** [radiorabe/rabe-zabbix#61]
I get this problem popping up all the time:
![image](https://user-images.githubusercontent.com/3813355/50473045-b7481680-09bb-11e9-988d-5881ac17f5ab.png)

CPU is measured in kbps (or am i wrong and thats ok?) like this:
![image](https://user-images.githubusercontent.com/3813355/50474964-39880900-09c3-11e9-9077-f05e9e589366.png)

I doubt cpu usage is always over 90%... Or do you know a method to check cpu utilization on this switch?

**Comment by hairmare** [comment]
At a glance it looks like one of the ports on your switch is labeled "cpu". I don't think the GST108Tv2 expose CPU utilization over snmp. I'll check to see if I have the same thing on our production.

**Comment by paraenggu** [comment]
@linuxlurak Note, that this is not the CPU utilization, but rather the CPU interface. The unit of the values are packets per second.

In case you are using the `Template Stack Netgear GS108Tv2 SNMPv2` template, consider to add a discovery filter which only includes the physical and LAG interfaces. Navigate to `Configuration > Templates > Template Stack Netgear GS108Tv2 SNMPv2 > Discovery rules > Network interfaces >  Filters` and add the following Filter:
```
Label    Macro                   Regular expression
A        {#SNMPVALUE}  matches   ^(g|l)[0-9]+$
```
The above filter should only discover interfaces named `g0`, `g1` `g2`, [...] and LAGs `l0`, `l1` `l2`, [...].

HTH.

**Comment by linuxlurak** [comment]
Thanks for your help. I'll check it out.

**Comment by paraenggu** [comment]
@linuxlurak Do you still experience problems with the monitoring of the CPU interface here, or can we close this? Thanks for your feedback.

**Comment by linuxlurak** [comment]
It works as it seems. "cpu" is not found anymore under "Items" of the device. Do you have a suggestion how to treat existing devices? Just delete the item?

**Comment by paraenggu** [comment]
> Do you have a suggestion how to treat existing devices? Just delete the item?

Either wait for the specific amount of days configured within the discovery rule under [_Keep lost resources period (in days)_](https://www.zabbix.com/documentation/3.0/manual/discovery/low_level_discovery#overview) (`Configuration / Templates / [TEMPLATE] / Discovery rules / [DISCOVERY RULE]`) or temporarily lower it to zero (0) to speed things up.

**Comment by paraenggu** [comment]
@linuxlurak can we close this, or are there any issues left? Thanks for your feedback.
