### ISSUE TITLE
Doesn't work under Zabbix 4.0

### ISSUE THREAD

**Issue by danboid** [radiorabe/rabe-zabbix#80]
I have installed this template under zabbix 4.0 and tested it with a Ubuntu 16.04 client (zabbix-agent) using mdadm raid 10. After installing the client config and resetting the zabbix agent on the client there are no errors in the agent log but I don't see any data relating to mdadm when I check out the "Latest data" page for the mdadm using zabbix client.

**Comment by danboid** [comment]
I should note that the Zabbix 'Template OS Linux' works fine with the same host, s the client seems to be working.

**Comment by paraenggu** [comment]
Hi @danboid 

> I have installed this template under zabbix 4.0 and tested it with a Ubuntu 16.04 client (zabbix-agent)

I assume that you have installed the [App MD-RAID Template](../tree/master/app/MD-RAID), is that correct?

Please note, that we haven't found the time yet to port the templates to Zabbix 4.0. However, they should probably still work.

Could you please check if the MDM items have been discovered and if you see any errors on the auto discovered items on you host?

Additionally, you could try to debug the parameters manually:
```bash
su -c 'zabbix_agentd -t rabe.raid.md.raid-device.discovery' -s /bin/bash zabbix
su -c 'zabbix_agentd -t rabe.raid.md.component-device.discovery' -s /bin/bash zabbix

/usr/bin/find -L /sys/block/ -maxdepth 2 -type d -name md
/usr/bin/find -L /sys/block/ -maxdepth 3 -type d -path '*/md/rd[0-9]*'
```

**Comment by danboid** [comment]
Hi @paraenggu !

Yes, it is your App MD-RAID Template I am trying to use.

"Could you please check if the MDM items have been discovered and if you see any errors on the auto discovered items on you host?"

How exactly? I am very new to Zabbix so I'm still learning the basics.

```
root@apollo:~# su -c 'zabbix_agentd -t rabe.raid.md.raid-device.discovery' -s /bin/bash zabbix
rabe.raid.md.raid-device.discovery            [t|{"data":[{"{#MD_RAID_RAID_DEV_NAME}":"md0"}]}]
root@apollo:~# 
root@apollo:~# su -c 'zabbix_agentd -t rabe.raid.md.component-device.discovery' -s /bin/bash zabbix
rabe.raid.md.component-device.discovery       [t|{"data":[{"{#MD_RAID_RAID_DEV_NAME}":"md0","{#MD_RAID_COMPONENT_DEV_NAME}":"rd0"},{"{#MD_RAID_RAID_DEV_NAME}":"md0","{#MD_RAID_COMPONENT_DEV_NAME}":"rd1"},{"{#MD_RAID_RAID_DEV_NAME}":"md0","{#MD_RAID_COMPONENT_DEV_NAME}":"rd2"},{"{#MD_RAID_RAID_DEV_NAME}":"md0","{#MD_RAID_COMPONENT_DEV_NAME}":"rd3"}]}]
root@apollo:~# 
root@apollo:~# /usr/bin/find -L /sys/block/ -maxdepth 2 -type d -name md
/sys/block/md0/md
root@apollo:~# 
root@apollo:~# /usr/bin/find -L /sys/block/ -maxdepth 3 -type d -path '*/md/rd[0-9]*'
/sys/block/md0/md/rd0
/sys/block/md0/md/rd1
/sys/block/md0/md/rd2
/sys/block/md0/md/rd3
...
```

As I said in my OP, I was expecting to see some MD-RAID related data when I check out the "Latest data" page for the mdadm using zabbix client (apollo, in this case). Maybe I'm looking in the wrong place?

**Comment by danboid** [comment]
I've found the MD discovery rules on the zabbix server

![Screenshot at 2019-05-30 12-18-51](https://user-images.githubusercontent.com/1429783/58629762-417f0880-82d5-11e9-881b-8ed379fcacc3.png)

**Comment by danboid** [comment]
If I select either of those discovery rules then click "Check now" zabbix returns the error

```
Cannot send request: wrong discovery rule type.
```

**Comment by paraenggu** [comment]
> ```
> root@apollo:~# su -c 'zabbix_agentd -t rabe.raid.md.raid-device.discovery' -s /bin/bash zabbix
> rabe.raid.md.raid-device.discovery            [t|{"data":[{"{#MD_RAID_RAID_DEV_NAME}":"md0"}]}]
> root@apollo:~# 
> root@apollo:~# su -c 'zabbix_agentd -t rabe.raid.md.component-device.discovery' -s /bin/bash zabbix
> rabe.raid.md.component-device.discovery       [t|{"data":[{"{#MD_RAID_RAID_DEV_NAME}":"md0","{#MD_RAID_COMPONENT_DEV_NAME}":"rd0"},{"{#MD_RAID_RAID_DEV_NAME}":"md0","{#MD_RAID_COMPONENT_DEV_NAME}":"rd1"},{"{#MD_RAID_RAID_DEV_NAME}":"md0","{#MD_RAID_COMPONENT_DEV_NAME}":"rd2"},{"{#MD_RAID_RAID_DEV_NAME}":"md0","{#MD_RAID_COMPONENT_DEV_NAME}":"rd3"}]}]
> root@apollo:~# 
> root@apollo:~# /usr/bin/find -L /sys/block/ -maxdepth 2 -type d -name md
> /sys/block/md0/md
> root@apollo:~# 
> root@apollo:~# /usr/bin/find -L /sys/block/ -maxdepth 3 -type d -path '*/md/rd[0-9]*'
> /sys/block/md0/md/rd0
> /sys/block/md0/md/rd1
> /sys/block/md0/md/rd2
> /sys/block/md0/md/rd3
> ...
> ```

Good, so the low-level discovery user parameters are working on this host.

On your previous screenshot I see the `App MD RAID active` template and not the actual host discovery rules.
Just to make sure: You've added the `App MD RAID active` template directly or indirectly to your host (`apollo`), is that correct?

Could you please post a screenshot of your host's discovery rules overview?

**Comment by danboid** [comment]
![Screenshot from 2019-05-31 12-34-08](https://user-images.githubusercontent.com/1429783/58703432-90de3b00-83a0-11e9-86c2-54c98d9aefca.png)

**Comment by paraenggu** [comment]
OK this looks good, the template is available on your host.

I see that you use passive checks for the other discovery rules. The `App MD RAID active` template uses [active checks](https://www.zabbix.com/documentation/3.0/manual/appendix/items/activepassive#active_checks).

Have you specified your Zabbix server(s) within the [` ServerActive`](https://www.zabbix.com/documentation/4.0/manual/appendix/config/zabbix_agentd) directive on the Zabbix agent's configuration (`zabbix_agentd.conf`) on `apollo`? Alternatively, you would have to change all items from active to passive within the `App MD RAID active` template.

**Comment by danboid** [comment]
Yes, that was my issue! My agents are only configured to use passive monitoring currently so I changed all the MD RAID discovery rules and item prototypes to type 'Zabbix' (instead of 'Zabbix active') and I am receiving MD RAID data now.

Thanks for your help!

**Comment by paraenggu** [comment]
Thanks @danboid for the feedback - I'm glad to read that the template is working now on your environment!
