### ISSUE TITLE
app/LVM is working fine in Zabbix 4.0 LTS

### ISSUE THREAD

**Issue by tschaerni** [radiorabe/rabe-zabbix#82]
I don't know if you get that much feedback, I just wanted to point out that the LVM template works like it should in Zabbix 4.0 (on the zabbix-share site of the project it mentioned Zabbix 3.0.x)

Cheers!
- tschaerni

**Comment by hairmare** [comment]
Hey @tschaerni 

Thank you very much for the feedback. We mostly get support requests through here so your positive feedback is very much appreciated.

Our current production is still on 3.0.x as we haven't gotten around to updating our critical monitoring. We'll probably update the zabbix-share descriptions once we've updated our prod.

Again, thanks for the feedback.
Lucas

**Comment by tschaerni** [comment]
I just recently installed Zabbix 4.0 LTS for my (now rather large) private infrastructure, and just recently upgraded at work from 3.0 to 4.0. There wasn't really any problems (apart from reinstalling some zabbix packages, because debian...). I even consider using some of your templates at work. And I will definitely replace my current md-raid template with yours, it's much more streamlined and has more (for me important) features than the one I use atm.

I'm still trying to learn how to create item/trigger prototypes and how the do the LLD correctly. I'm working at a template for monitoring of BorgBackup --> [https://borgbackup.readthedocs.io/en/stable/](url)

Anyway, I also just wanted to thank for the good documentation!
Keep up the good work!
- tschaerni
