### ISSUE TITLE
LVM unavailable options

### ISSUE THREAD

**Issue by Richie765** [radiorabe/rabe-zabbix#90]
Hello! I'm trying to use the LVM app. It looks well thought out and well documented. I got most of it working, like discovery. Many items work fine as well, but some don't. 

When I looked into it, it seems my 'lvs' does not support some -o options, specifically: data_user, metadata_free, metadata_free_percent, data_free_percent, data_free. There may be more, but these are the ones I'd like to use.

They also don't show up in `lvs -o help`. I'm using lvm2 version 2.03 on Ubuntu. I also looked on a Centos server, but it looks like the options aren't there as well.

Are you using a different lvs tool? Do you have any idea how to make this working?

Thanks!

**Comment by paraenggu** [comment]
Hi @Richie765 

> Many items work fine as well, but some don't.

What's not working and what error messages do you observe?


> When I looked into it, it seems my 'lvs' does not support some -o options, specifically: data_user, metadata_free, metadata_free_percent, data_free_percent, data_free.

The mentioned items are [calculated Zabbix items](https://www.zabbix.com/documentation/3.0/manual/config/items/itemtypes/calculated) based on other Zabbix items, Thus, you can't use them directly as a parameter for  `lvs -o`.

For example, the [Free meta data of thin-pool LV {#LVM_LV_FULL_NAME}](https://github.com/radiorabe/rabe-zabbix/blob/594e8728ada10780e0e28402736e0aa46cb03956/app/LVM/Template_App_LVM_active.xml#L1136-L1179) (`rabe.lvm.lvs.value[{#LVM_LV_FULL_NAME},metadata_free,thin-pool]`) item is calculated according to the following formula and items:
```
last("rabe.lvm.lvs.value[{#LVM_LV_FULL_NAME},lv_metadata_size,thin-pool]") - last("rabe.lvm.lvs.value[{#LVM_LV_FULL_NAME},metadata_used,thin-pool]")
```


In a first step, I would check that the items which are used within a calculated Zabbix item are working and data is available.

**Comment by Richie765** [comment]
Ok, got it! In my template those items weren't calculated items. I re-imported the template and now it works fine. I don't know how it happened. I imported the template a while ago. Anyway it works fine now! Thanks, also for making this available. Very useful!
